export const config = {
  source: ["pl", "en", "uk", "de", "cz", "fr", "lt", "ro", "sk", "hu", "it", "bg", "ua", "fi", "gr", "pt", "es", "ee", "hr", "lv", "nl", "me", "rs", "be", "at", "ie", "si"],
  mailing: {
    subject: "Price Change Podlasiak",
    clients: [
      { lang: "pl", emails: ["drteski@gmail.com", "teski666@gmail.com"] },
      { lang: "uk", emails: [] },
      { lang: "en", emails: [] },
      { lang: "de", emails: ["drteski@gmail.com", "teski666@gmail.com"] },
      { lang: "cz", emails: [] },
      { lang: "fr", emails: ["drteski@gmail.com", "teski666@gmail.com"] },
      { lang: "lt", emails: [] },
      { lang: "ro", emails: [] },
      { lang: "sk", emails: [] },
      { lang: "hu", emails: [] },
      { lang: "it", emails: [] },
      { lang: "bg", emails: [] },
      { lang: "ua", emails: [] },
      { lang: "fi", emails: [] },
      { lang: "gr", emails: [] },
      { lang: "pt", emails: [] },
      { lang: "es", emails: [] },
      { lang: "ee", emails: [] },
      { lang: "hr", emails: [] },
      { lang: "lv", emails: [] },
      { lang: "nl", emails: [] },
      { lang: "me", emails: [] },
      { lang: "rs", emails: [] },
      { lang: "be", emails: [] },
      { lang: "at", emails: [] },
      { lang: "ie", emails: [] },
      { lang: "si", emails: [] },
    ],
  },
  tariff: [
    {
      tariff: 1,
      lang: "pl",
      tax: 23,
      currency: "PLN",
    },
    {
      tariff: 2,
      lang: "en",
      tax: 20,
      currency: "GBP",
    },
    {
      tariff: 3,
      lang: "de",
      tax: 19,
      currency: "EUR",
    },
    {
      tariff: 4,
      lang: "ru",
      tax: 20,
      currency: "USD",
    },
    {
      tariff: 5,
      lang: "cz",
      tax: 21,
      currency: "CZK",
    },
    {
      tariff: 6,
      lang: "fr",
      tax: 20,
      currency: "EUR",
    },
    {
      tariff: 7,
      lang: "lt",
      tax: 21,
      currency: "EUR",
    },
    {
      tariff: 8,
      lang: "ro",
      tax: 19,
      currency: "RON",
    },
    {
      tariff: 9,
      lang: "sk",
      tax: 20,
      currency: "EUR",
    },
    {
      tariff: 10,
      lang: "hu",
      tax: 27,
      currency: "HUF",
    },
    {
      tariff: 11,
      lang: "it",
      tax: 22,
      currency: "EUR",
    },
    {
      tariff: 12,
      lang: "bg",
      tax: 20,
      currency: "BGN",
    },
    {
      tariff: 13,
      lang: "ua",
      tax: 20,
      currency: "EUR",
    },
    {
      tariff: 14,
      lang: "es",
      tax: 21,
      currency: "EUR",
    },
    {
      tariff: 17,
      lang: "hr",
      tax: 25,
      currency: "EUR",
    },
    {
      tariff: 18,
      lang: "nl",
      tax: 21,
      currency: "EUR",
    },
    {
      tariff: 20,
      lang: "me",
      tax: 21,
      currency: "EUR",
    },
    {
      tariff: 21,
      lang: "be",
      tax: 21,
      currency: "EUR",
    },
    {
      tariff: 22,
      lang: "at",
      tax: 20,
      currency: "EUR",
    },
    {
      tariff: 23,
      lang: "rs",
      tax: 20,
      currency: "RSD",
    },
    {
      tariff: 24,
      lang: "ie",
      tax: 23,
      currency: "EUR",
    },
    {
      tariff: 25,
      lang: "si",
      tax: 22,
      currency: "EUR",
    },
    {
      tariff: 26,
      lang: "ee",
      tax: 20,
      currency: "EUR",
    },
    {
      tariff: 27,
      lang: "lv",
      tax: 21,
      currency: "EUR",
    },
    {
      tariff: 30,
      lang: "pt",
      tax: 23,
      currency: "EUR",
    },
    {
      tariff: 31,
      lang: "fi",
      tax: 24,
      currency: "EUR",
    },
    {
      tariff: 32,
      lang: "gr",
      tax: 24,
      currency: "EUR",
    },
  ],
};
