export const config = {
  data: [
    { iso: "pl", password: "Pontony!88<", name: "Poland", currency: "PLN", locale: "pl-PL" },
    { iso: "en", password: "Pontony!88<", name: "England", currency: "GBP", locale: "en-GB" },
    { iso: "de", password: "Pontony!88<", name: "Germany", currency: "EUR", locale: "de-DE" },
    { iso: "cz", password: "Pontony!88<", name: "Czech", currency: "CZK", locale: "cz-CZ" },
    { iso: "fr", password: "Pontony!88<", name: "France", currency: "EUR", locale: "fr-FR" },
    { iso: "lt", password: "Pontony!88<", name: "Lithuania", currency: "EUR", locale: "lt-LT" },
    { iso: "ro", password: "Pontony!88<", name: "Romania", currency: "RON", locale: "ro-RO" },
    { iso: "sk", password: "Pontony!88<", name: "Slovakia", currency: "EUR", locale: "sk-SK" },
    { iso: "hu", password: "Pontony!88<", name: "Hungary", currency: "HUF", locale: "hu-HU" },
    { iso: "it", password: "Pontony!88<", name: "Italy", currency: "EUR", locale: "it-IT" },
    { iso: "bg", password: "Pontony!88<", name: "Bulgaria", currency: "BGN", locale: "bg-BG" },
    { iso: "ua", password: "Pontony!88<", name: "Ukraine", currency: "EUR", locale: "ua-UA" },
    { iso: "es", password: "Pontony!88<", name: "Spain", currency: "EUR", locale: "es-ES" },
    { iso: "ee", password: "Pontony!88<", name: "Estonia", currency: "EUR", locale: "et-EE" },
    { iso: "hr", password: "Pontony!88<", name: "Croatia", currency: "EUR", locale: "hr-HR" },
    { iso: "lv", password: "Pontony!88<", name: "Latvia", currency: "EUR", locale: "lv-LV" },
    { iso: "nl", password: "Pontony!88<", name: "Netherlands", currency: "EUR", locale: "nl-NL" },
    { iso: "me", password: "Pontony!88<", name: "Montenegro", currency: "EUR", locale: "sr-ME" },
    { iso: "rs", password: "Pontony!88<", name: "Serbia", currency: "EUR", locale: "sr-RS" },
    { iso: "be", password: "Pontony!88<", name: "Belgium", currency: "EUR", locale: "fr-BE" },
    { iso: "at", password: "Pontony!88<", name: "Austria", currency: "EUR", locale: "de-AT" },
    { iso: "ie", password: "Pontony!88<", name: "Ireland", currency: "EUR", locale: "en-IE" },
    { iso: "si", password: "Pontony!88<", name: "Slovenia", currency: "EUR", locale: "si-SI" },
    { iso: "pt", password: "Pontony!88<", name: "Portuguese", currency: "EUR", locale: "pt-PT" },
    { iso: "fi", password: "Pontony!88<", name: "Finland", currency: "EUR", locale: "fi-FI" },
    { iso: "gr", password: "Pontony!88<", name: "Greece", currency: "EUR", locale: "gr-GR" },
  ],
  translations: [
    { iso: "pl", subject: "Zmiany cen | Podlasiak" },
    { iso: "en", subject: "Price Changes | Podlasiak" },
    { iso: "uk", subject: "Зміни цін | Podlasiak" },
    { iso: "de", subject: "Preisänderungen | Podlasiak" },
    { iso: "cz", subject: "Změny cen | Podlasiak" },
    { iso: "fr", subject: "Changements de prix | Podlasiak" },
    { iso: "lt", subject: "Kainų pokyčiai | Podlasiak" },
    { iso: "ro", subject: "Schimbări de preț | Podlasiak" },
    { iso: "sk", subject: "Zmeny cien | Podlasiak" },
    { iso: "hu", subject: "Árváltozások | Podlasiak" },
    { iso: "it", subject: "Cambiamenti di prezzo | Podlasiak" },
    { iso: "bg", subject: "Промени в цените | Podlasiak" },
    { iso: "ua", subject: "Зміни цін | Podlasiak" },
    { iso: "fi", subject: "Hintamuutokset | Podlasiak" },
    { iso: "gr", subject: "Αλλαγές τιμών | Podlasiak" },
    { iso: "pt", subject: "Alterações de preços | Podlasiak" },
    { iso: "es", subject: "Cambios de precios | Podlasiak" },
    { iso: "ee", subject: "Hinnamuutused | Podlasiak" },
    { iso: "hr", subject: "Promjene cijena | Podlasiak" },
    { iso: "lv", subject: "Cenu izmaiņas | Podlasiak" },
    { iso: "nl", subject: "Prijswijzigingen | Podlasiak" },
    { iso: "me", subject: "Promjene cijena | Podlasiak" },
    { iso: "rs", subject: "Promene cena | Podlasiak" },
    { iso: "be", subject: "Prijzen veranderen | Podlasiak" },
    { iso: "at", subject: "Preisänderungen | Podlasiak" },
    { iso: "ie", subject: "Price Changes | Podlasiak" },
    { iso: "si", subject: "Spremembe cen | Podlasiak" },
  ],
  tariff: [
    {
      tariff: 1,
      lang: "pl",
      tax: 23,
      currency: "PLN",
    },
    {
      tariff: 2,
      lang: "en",
      tax: 20,
      currency: "GBP",
    },
    {
      tariff: 3,
      lang: "de",
      tax: 19,
      currency: "EUR",
    },
    {
      tariff: 4,
      lang: "ru",
      tax: 20,
      currency: "USD",
    },
    {
      tariff: 5,
      lang: "cz",
      tax: 21,
      currency: "CZK",
    },
    {
      tariff: 6,
      lang: "fr",
      tax: 20,
      currency: "EUR",
    },
    {
      tariff: 7,
      lang: "lt",
      tax: 21,
      currency: "EUR",
    },
    {
      tariff: 8,
      lang: "ro",
      tax: 19,
      currency: "RON",
    },
    {
      tariff: 9,
      lang: "sk",
      tax: 20,
      currency: "EUR",
    },
    {
      tariff: 10,
      lang: "hu",
      tax: 27,
      currency: "HUF",
    },
    {
      tariff: 11,
      lang: "it",
      tax: 22,
      currency: "EUR",
    },
    {
      tariff: 12,
      lang: "bg",
      tax: 20,
      currency: "BGN",
    },
    {
      tariff: 13,
      lang: "ua",
      tax: 20,
      currency: "EUR",
    },
    {
      tariff: 14,
      lang: "es",
      tax: 21,
      currency: "EUR",
    },
    {
      tariff: 17,
      lang: "hr",
      tax: 25,
      currency: "EUR",
    },
    {
      tariff: 18,
      lang: "nl",
      tax: 21,
      currency: "EUR",
    },
    {
      tariff: 20,
      lang: "me",
      tax: 21,
      currency: "EUR",
    },
    {
      tariff: 21,
      lang: "be",
      tax: 21,
      currency: "EUR",
    },
    {
      tariff: 22,
      lang: "at",
      tax: 20,
      currency: "EUR",
    },
    {
      tariff: 23,
      lang: "rs",
      tax: 20,
      currency: "RSD",
    },
    {
      tariff: 24,
      lang: "ie",
      tax: 23,
      currency: "EUR",
    },
    {
      tariff: 25,
      lang: "si",
      tax: 22,
      currency: "EUR",
    },
    {
      tariff: 26,
      lang: "ee",
      tax: 20,
      currency: "EUR",
    },
    {
      tariff: 27,
      lang: "lv",
      tax: 21,
      currency: "EUR",
    },
    {
      tariff: 30,
      lang: "pt",
      tax: 23,
      currency: "EUR",
    },
    {
      tariff: 31,
      lang: "fi",
      tax: 24,
      currency: "EUR",
    },
    {
      tariff: 32,
      lang: "gr",
      tax: 24,
      currency: "EUR",
    },
  ],
};
